server:
  port: 8080
  tomcat:
    max-threads: 300

spring:
  application:
    name: cine-application
  data:
    rest:
      default-page-size: 40
      max-page-size: 1000
      default-media-type: application/json
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2121/cine
    username: postgres
    password: Edisonmesa2105
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



